site_name: MERN Web Technologies
theme:
  name: material
nav:
  - Home: index.md
  - Web Foundations:
      - Overview: 01-web-foundations/overview.md
      - Web Architectures: 01-web-foundations/web-architectures.md
      - Technology Overview: 01-web-foundations/technology-overview.md
      - HTML/CSS: 01-web-foundations/html_css_chapter.md
  - HTML & CSS:
      - Fundamentals: 02-html/index.md
      - HTML CSS Demos: 02-html/html-css-demos.md
  - JavaScript: 03-javascript/index.md
  - Node.js & Express: 04-node/index.md
  - React: 05-react/index.md
  - Slides: slides/index.md
  - Blog: https://usmanlive.com
markdown_extensions:
  - fenced_code
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/javascripts/mermaid-init.js
